# This is a basic workflow to help you get started with Actions

name: cocoafei.top

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 21 * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Runs a single command using the runners shell
      # - name: Run a one-line script
      #   run: echo $(curl -I -m 15 -s -w "%{http_code}\n" -o /dev/null  cocoafei.top) > status_code.txt
      
      # Runs a set of commands using the runners shell
      - name: Get cocoafei.top response status code.
        env:
          username: ${{secrets.MAIL_USERNAME}}
        run: |
          export status_code=$(curl -I -m 15 -s -w "%{http_code}\n" -o /dev/null  cocoafei.top)
          echo "abccc${{secrets.MAIL_USERNAME}}+"${{secrets.MAIL_USERNAME}}
          python ./status_email.py ${{secrets.MAIL_USERNAME}} ${{secrets.MAIL_PASSWORD}} 404

      # Send email
      # - name: Send mail
      #   uses: dawidd6/action-send-mail@v2
      #   with:
      #     server_address: smtp.qq.com
      #     server_port: 587
      #     username: ${{secrets.MAIL_USERNAME}}
      #     password: ${{secrets.MAIL_PASSWORD}}
      #     subject: Github Actions - ping cocoafei.top
      #     body: file://status_code.txt
      #     to: lifei_zdjl@qq.com,lifei_zdjl@126.com
      #     from: Github Actions
